[package]
name = "indexer"
version = "0.1.2"
edition = "2021"

resolver = "1"

[dependencies]
anyhow = "1.0.98"
chrono = { version = "0.4.41", features = ["serde"] }
ignore = "0.4.23"
memchr = "2.7.5"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
sha1 = "0.10.6"
